### PR TITLE
Fix session glitch

### LINKED ISSUE #134: How to use filter :login_again_if_different_shop
Hi,

I want to use __login_again_if_different_shop__ in my app. 
```ruby
def login_again_if_different_shop
  if shop_session && params[:shop] && params[:shop].is_a?(String) && shop_session.url != params[:shop]
    redirect_to_login
  end
end
```
I've added it like following:
```ruby
class ApplicationController < ActionController::Base
  before_filter :login_again_if_different_shop
```
```ruby
class SessionsController < ApplicationController
  skip_before_filter :login_again_if_different_shop
```
for now, I opened my app in Shop A, then open a new window(Chrome tab) to access my app in Shop B. 
the code always capture the url of Shop A from params[:shop], so redirect to Shop A.

If I remove __skip_before_filter__ from SessionsController then get the __Too many redirects__ error.
How to make it switch to the Shop B automatically?

### PR DESCRIPTION
**Pull request by qq99**
Fixes #134 (I'm 99% sure)

Fixes a session glitch where another return_to URL would be stored from a previous request by the same browser

cc @kevinhughes27

### CODE REVIEW

File: lib/shopify_app/sessions_controller.rb [hunk 1]
```diff
@@ -16,6 +16,7 @@ def callback
         sess = ShopifyAPI::Session.new(shop_name, response['credentials']['token'])
         session[:shopify] = ShopifyApp::SessionRepository.store(sess)
         session[:shopify_domain] = shop_name
+        session[:return_to] = nil
```
Comment (kevinhughes27) [inline lib/shopify_app/sessions_controller.rb]: err now `redirect_to return_address` won't work at all. We need to pop this out of the session so we can use it and delete it

Comment (qq99) [inline lib/shopify_app/sessions_controller.rb]: won't it fall back to `main_app.root_url`?

Comment (kevinhughes27) [inline lib/shopify_app/sessions_controller.rb]: yeah but if return_to was actually set now we have unset and not used it.

I think the solution here is just to clean this up after we've used it is all.

Comment (qq99) [inline lib/shopify_app/sessions_controller.rb]:
```ruby
    def return_address
      session.delete(:return_to) || main_app.root_url
    end
```
like such?

Comment (qq99) [inline lib/shopify_app/sessions_controller.rb]: I'm not really familiar with OAuth

**Comment by qq99** [comment]
Tweaked @kevinhughes27 how is this?

File: lib/shopify_app/sessions_controller.rb (hunk 1 above)
Comment (kevinhughes27) [inline lib/shopify_app/sessions_controller.rb]: Its complicated stuff because there are so many possible states. I don't think what you've got there is correct because we only want to clear it in the callback endpoint. We want it to carry through the other ones

**Comment by kevinhughes27** [comment]
:+1: ignore my other comment this works since we only call `return_address` when we are done an oauth flow (or exit early)

**Comment by qq99** [comment]
cool I also moved to a `.delete` and didn't `nil` it out anymore
