### PR TITLE
prevents shop params from being dropped on second installation attempt

### LINKED ISSUE #245: Uninstall app, re-install again redirects without oauth
I'm so stumped on this issue.  I got rejected from the beta approval and really want to get this in. I appreciate anyone can help.

Steps to reproduce
---------------------------
1. Install app
2. Remove app
3. Install app again

Expected: Send to "Install app" prompt screen
Result: The default /login with the input box

If I re-install again, then it shows properly.  It happens exactly once after the app is removed.

Gem: ShopApp 6.4.2

Logs
-------------------------

From the logs, you can clearly see the request shows shopify_domain, redirected, and the domain gets lost.

```
Started GET "/main?hmac=d65d07d6ae0fb25d1b89c5aa2ea7afdeaea2c338a25800ede276679dc3c14437&shop=teststorequoc.myshopify.com&signature=ff49dfcd7a0e7df52bface23eefa2221&timestamp=1459878395" for 12.251.228.138 at 2016-04-05 17:17:54 -0700
Cannot render console from 12.251.228.138! Allowed networks: 127.0.0.1, ::1, 127.0.0.0/127.255.255.255
Processing by HomeController#index as HTML
  Parameters: {"hmac"=>"d65d07d6ae0fb25d1b89c5aa2ea7afdeaea2c338a25800ede276679dc3c14437", "shop"=>"teststorequoc.myshopify.com", "signature"=>"ff49dfcd7a0e7df52bface23eefa2221", "timestamp"=>"1459878395"}
  Shop Load (0.2ms)  SELECT  "shops".* FROM "shops" WHERE "shops"."id" = $1 LIMIT 1  [["id", 4]]
  Shop Load (0.2ms)  SELECT  "shops".* FROM "shops" WHERE "shops"."shopify_domain" = $1 LIMIT 1  [["shopify_domain", "teststorequoc.myshopify.com"]]
Redirected to https://b4d3b2af.ngrok.io/login
Completed 302 Found in 448ms (ActiveRecord: 0.5ms)

Started GET "/login" for 12.251.228.138 at 2016-04-05 17:17:54 -0700
Cannot render console from 12.251.228.138! Allowed networks: 127.0.0.1, ::1, 127.0.0.0/127.255.255.255
Processing by SessionsController#new as HTML
  Rendered sessions/new.html.erb within layouts/application (0.1ms)
Completed 200 OK in 117ms (Views: 116.5ms | ActiveRecord: 0.0ms)
```

### PR DESCRIPTION
**Pull request by jordanliddle**
This fixes #245 by ensuring that the shop params are passed when the app is uninstalled, but session persists.

[Screencast here](https://screenshot.click/24-12-1dekx-sljz3.mp4)

@kevinhughes27, @jamiemtdwyer for 👀

### CODE REVIEW

**Comment by jamiemtdwyer** [comment]
🎩 with @jordanliddle, LGTM :+1:

File: test/shopify_app/login_protection_test.rb [hunk 1]
```diff
@@ -86,13 +90,21 @@ class LoginProtectionTest < ActionController::TestCase
     end
   end
 
+  test '#shopify_session when rescuing from unauthorized access, redirects to the login url' do
+    with_application_test_routes do
+      get :raise_unauthorized, shop: 'foobar'
+      assert_redirected_to @controller.send(:main_or_engine_login_url, shop: 'foobar')
+    end
+  end
```
Comment (kevinhughes27) [inline test/shopify_app/login_protection_test.rb]: I just double checked what the behaviour is with an empty shop param and it should work: https://github.com/Shopify/shopify_app/blob/master/lib/shopify_app/sessions_concern.rb#L6. We have tests for this in the session controller test

**Comment by kevinhughes27** [comment]
👍  Thanks guys!

**Comment by mhaylock** [comment]
I [implemented this same fix today](https://github.com/Shopify/shopify_app/commit/561cdafdfddee908d57282cb104f1c22cdf7770d) (including writing the missing test) - my fault for not looking through the open pull requests properly.

Any idea when this might be merged? Is there anything outstanding needed before it can be?

**Comment by kevinhughes27** [comment]
ping @jordanliddle

**Comment by kevinhughes27** [comment]
@mhaylock thanks for the ping this slipped through the cracks somehow.

**Comment by adamw005** [comment]
I am running into this error on v7.0.2 'undefined local variable or method `login_url' for #<TestController:0x007fcd92e19918>' on line 49 of login_protection.rb 'redirect_to_with_fallback login_url'

It looks like this update fixes this, but in order to get shopify_app >=7.0.9 I would need to update rails to 4.2.6 and ruby to 2.2. Is there an easier way to get this one patch working? I'm using heroku and can't push local gem changes

**Comment by kevinhughes27** [comment]
I believe the rails version is spec'd due to a security vuln so it would not be advised to do so. There were no breaking changes in that version of rails so there is no reason not to upgrade.

You can always fork a gem and use a github dep if you need to.
